source "https://rubygems.org"
gem "mechanize"
gem "progress_bar"
gem "highline"
gem "chronic"
gem "time-lord"
gem "pg"
gem "rufus-scheduler", '2.0.24'
gem "sequel"
gem "uuidtools"
gem "bloat_check"
gem "lingua"
gem "watir-webdriver"
