---
:geo:
  :distance_filter_type: state
  :preferred_state: California
  :preferred_city: San Diego
  :distance: 8000
:matching:
  :min_percent: 50
  :friend_percent: 0
  :enemy_percent: 0
  :min_age: 18
  :max_age: 45
  :age_sort: ASC #or DESC. ASC prefer younger
  :gender: F
  :max_height: 1.7 #in meters
  :min_height: 0 #in meters
  :height_sort: ASC #or DESC. ASC prefer shorter
  :last_online_cutoff: 365 # don't visit if not last online since X days ago
:visit_freq:
  :days_ago: 3
  :max_followup: 15
:scraping:
  :autodiscover_on: true
:growl:
    :new_visits: false
    :new_mail: true
    :favorite_sign_on: false
    :favorite_sign_off: false
    :new_im: false
:development:
  :verbose: true
  :debug: false
